### ISSUE TITLE
Ios 18 , Xcode 16 issuse when archive

### ISSUE THREAD

**Issue by AlaaQutishat** [ahmedelkhyary/hyperpay_sdk#7]
When try make Archive show this 

Asset validation failed Invalid Executable. The executable 'Runner.app/Frameworks/ipworks3ds_sdk.framework/ipworks3ds_sdk' contains bitcode. (ID: 16d43e94-b712-4528-b0d1-7662582f7558)

**Comment by leithalnajjar** [comment]
any update?

**Comment by ahmedelkhyary** [comment]
check please update new version 3.0.0 @leithalnajjar @AlaaQutishat
