### ISSUE TITLE
CocoaPods could not find compatible versions for pod "hyperpay_sdk":

### ISSUE THREAD

**Issue by AbdallahDafa** [ahmedelkhyary/hyperpay_sdk#8]
My Xcode 16.0, print error after update xcode :
Pre-downloading: `hyperpay_sdk` from `https://github.com/ahmedelkhyary/hyperpay_sdk.git`
[!] CocoaPods could not find compatible versions for pod "hyperpay_sdk":
  In Podfile:
    hyperpay_plugin (from `.symlinks/plugins/hyperpay_plugin/ios`) was resolved to 0.0.3, which depends on
      hyperpay_sdk (~> 5.1.0)

    hyperpay_sdk (from `https://github.com/ahmedelkhyary/hyperpay_sdk.git`)

**Comment by ahmedelkhyary** [comment]
Dear @AbdallahDafa  

remove Podfile.lock and pod install again 
use last version 3.0.0

**Comment by AbdallahDafa** [comment]
I am already make remove pods before install againBy command remove all pod filesGet Outlook for AndroidFrom: Ahmed Elkhyary ***@***.***>Sent: Thursday, November 14, 2024 11:46:55 AMTo: ahmedelkhyary/hyperpay_sdk ***@***.***>Cc: Abdallah Mahmoud ***@***.***>; Mention ***@***.***>Subject: Re: [ahmedelkhyary/hyperpay_sdk] CocoaPods could not find compatible versions for pod "hyperpay_sdk": (Issue #8)
Closed #8 as completed.

**Comment by AbdallahDafa** [comment]
not soled yet
